services:
  monitor:
    build:
      context: ./manager/monitor
      dockerfile: ../../Dockerfile

  analyze:
    build:
      context: ./manager/analyze
      dockerfile: ../../Dockerfile

  plan:
    build:
      context: ./manager/plan
      dockerfile: ../../Dockerfile

  knowledge:
    build:
      context: ./manager/knowledge
      dockerfile: ../../Dockerfile

  execute:
    build:
      context: ./manager/execute
      dockerfile: ../../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - core
      - knowledge

  provider:
    build:
      context: ./managed/provider
      #dockerfile: ../../Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENABLE_PDFA=${ENABLE_PDFA:-false}

  core:
    build:
      context: ./managed/core
      dockerfile: ../../Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - knowledge